blank_issues_enabled: false
contact_links:
  - name: Security policy
    url: https://github.com/ehsanghaffarii/nextjs-starter/security/policy
    about: Please follow the security policy for vulnerability reports.

